Luồng xử lí
longqt321/PBL2 pull request #4
Opened 2024-10-28 08:06 UTC by LuanNguyen23T

2024-10-28 22:54 UTC, longqt321 requested changes
Tôi có để comment chi tiết từng phần tôi muốn ông sửa rồi á, nếu có gì không rõ thì ông nhắn lên mess. Mỗi lần ông pull code thì nhắn lên mess 1 tiếng để tui check, chơ github hắn ko nhảy thông báo.
**QUAN TRỌNG**: Ông tìm hiểu về file .gitignore. Để khi pull code thì đừng có pull mấy file json với exe lên. Chỉ pull .cpp với .h lên giúp tôi.

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +    bool time = true, service = true;
Sử dụng tên biến khác cho time và service. Vì khi đọc time với service làm người ta tưởng rằng 2 cái này sẽ dùng để lưu thời gian hoặc dịch vụ chi đó, cơ mà ở đây ông lại dùng để lưu True với False thì không ổn cho lắm.

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +                if(!isValidService(services[i], chosenService[services[i]])){
Tương tự ở trên, bỏ phần tham số bool của hàm isValidService đi

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +    for(int i = 1; i < 8; i++){
Như tôi đã nói hôm trước ở trên mess. Không cần nhắc việc dịch vụ i được chọn mấy lần. Vì nếu chọn lại 1 dịch vụ đã chọn thì tức là người ta muốn hủy.

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +        cin.ignore(numeric_limits<streamsize>::max(), '\n');
Nên thêm comment cho các câu lệnh khó hiểu như này

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +        if(services.front() == 0){
Ở phần này, cho dù họ chưa chọn dịch vụ mô hết. Thì cũng cho họ thoát luôn, chứ không để họ mắc kẹt ở đó. Vì có khi người ta ấn nhầm vào chỗ đặt lịch chẳng hạn

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +        if(services.front() == 0){
Gọi hàm front của vector mà chưa check xem vector đó có rỗng hay không.
Ở trên web https://cplusplus.com/ ông có thể tìm được tài liệu về hàm front ni, hắn trả về 1 tham chiếu, và nếu vector rỗng thì sẽ xảy ra tình trạng undefined behaviour (Hiểu đơn giản là hành vi không xác định được, lúc đúng lúc sai, chạy máy mình thì đúng, chạy máy người khác thì sai, dùng compiler ni thì đúng, dùng compiler khác thì sai.  Nói chung là không đoán được kết quả)

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +            cin >> input;
Chưa validate input. 
Tôi thử nhập input = 10000000000000000000000000 thì chương trình crash ngay lập tức. Có 2 lý do
+ Kiểu int ko chứa nỗi số lớn như rứa => Hắn crash vì lý do ni, do cái ni chạy trước
Ngoài ra còn có 1 lý do tiềm ẩn khác là mảng count không chứa nỗi index lớn như rứa

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +    else if (!between(month, 1, 12))
Không phải lỗi, chỉ là sửa để cú pháp gọn gàng, dễ đọc hơn 
Ông không cần dùng "else" trong "else if" cũng được. Chỉ cần viết if mỗi dòng là đủ, do if ở trước mà chạy thì hắn đã return và thoát function rồi

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +    if (inputTimeT == -1 || inputTimeT < t)
Ông nên viết 1 cái comment để lần sau đọc còn hiểu đoạn code này đang làm gì. Mặc dù tra chatGPT được, cơ mà lúc show code khi thuyết trình thì comment sẽ giống như 'phao' á, để mình còn biết là lúc nớ mình viết mấy dòng ni để làm chi

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +            cin >> input;
Thật ra thì khá khó để validate cái vụ người dùng cố tình nhập '100000000000000000000000000000', vì hiện tại mình chỉ validate sau khi người dùng đã nhập xong, còn lúc đang nhập thì không kiểm soát được.
Mặc dù thực tế thì ít ai cố tình nhập như rứa, cơ mà giáo viên thì có thể  bắt mình làm rứa để xem mình có check mấy cái corner case kiểu như ri hay không.

Có 1 cách giải quyết đó là input sẽ là string thay vì int, vì string chắc chắn sẽ chứa được số lớn như rứa (mặc dù phải lưu hắn dưới dạng kí tự, chơ không phải số).

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +    cout << "Dịch vụ đã chọn: ";
Ở phần print ra các dịch vụ đã chọn ni, ông viết thành 1 function để code gọn hơn

2024-10-28 22:54 UTC, longqt321 commented on CRUD/Void.cpp
> +    cout << "\nThông tin lịch đặt hẹn:\n";
Tôi khá thích cái vụ confirm lại thông tin như ri, kiểu như họ book lịch xong thì mình cho họ 1 cái thẻ hay chi đó để khi tới tiệm thì họ show ra là biết họ có hẹn rồi á.

Ở dưới phần "Thông tin lịch hẹn", ông thêm tên khách hàng, số điện thoại (cứ thêm 2 dòng đó đi đã, còn data về tên với sđt ở đâu ra thì xử lý sau)

2024-11-06 10:06 UTC, LuanNguyen23T commented
こんにちは

2024-11-06 10:06 UTC, closed without merging